package com.nexopp.lan

import java.security.SecureRandom
import java.util.concurrent.ConcurrentHashMap

/**
 * Represents an active local pairing session.
 *
 * @param sessionToken Cryptographically strong 256-bit token (64 hex characters) generated by [SecureRandom].
 * @param pairingCode Short, human-friendly 8-character pairing code (e.g. "7K4M-92Q") for manual PC entry.
 * @param createdAt Epoch timestamp when the session was created.
 * @param expiresAt Epoch timestamp when the session expires.
 */
data class PairingSession(
    val sessionToken: String,
    val pairingCode: String,
    val createdAt: Long = System.currentTimeMillis(),
    val expiresAt: Long
) {
    val isExpired: Boolean
        get() = System.currentTimeMillis() > expiresAt
}

/**
 * Manages pairing sessions, tokens, and short codes strictly within the local device memory.
 * No external servers or remote registries are used.
 */
class PairingTokenManager(
    private val defaultSessionDurationMs: Long = 10 * 60 * 1000L // 10 minutes
) {
    private val secureRandom = SecureRandom()
    // Alphabet excluding ambiguous characters: 0, O, 1, I
    private val codeAlphabet = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"

    // Maps sessionToken -> PairingSession
    private val sessionsByToken = ConcurrentHashMap<String, PairingSession>()
    // Maps normalized pairingCode -> sessionToken
    private val tokensByCode = ConcurrentHashMap<String, String>()

    /**
     * Creates a new pairing session with a 256-bit session token and an 8-character pairing code.
     */
    fun createSession(durationMs: Long = defaultSessionDurationMs): PairingSession {
        cleanExpired()

        // 32 bytes = 256 bits of real cryptographic entropy
        val tokenBytes = ByteArray(32)
        secureRandom.nextBytes(tokenBytes)
        val sessionToken = tokenBytes.joinToString("") { "%02x".format(it) }

        // Short 8-character code formatted as XXXX-XXXX (e.g., "7K4M-92Q1" or 4+3 "7K4M-92Q")
        val part1 = buildString(4) {
            repeat(4) { append(codeAlphabet[secureRandom.nextInt(codeAlphabet.length)]) }
        }
        val part2 = buildString(3) {
            repeat(3) { append(codeAlphabet[secureRandom.nextInt(codeAlphabet.length)]) }
        }
        val pairingCode = "$part1-$part2"

        val now = System.currentTimeMillis()
        val session = PairingSession(
            sessionToken = sessionToken,
            pairingCode = pairingCode,
            createdAt = now,
            expiresAt = now + durationMs
        )

        sessionsByToken[sessionToken] = session
        tokensByCode[normalizeCode(pairingCode)] = sessionToken

        return session
    }

    /**
     * Validates whether the given [sessionToken] exists and has not expired.
     */
    fun validateToken(sessionToken: String?): Boolean {
        if (sessionToken.isNullOrBlank()) return false
        val session = sessionsByToken[sessionToken] ?: return false
        if (session.isExpired) {
            revokeSession(sessionToken)
            return false
        }
        return true
    }

    /**
     * Validates a short pairing code entered by the user in the PC browser.
     * Returns the corresponding [sessionToken] if valid, or null if invalid/expired.
     */
    fun validatePairingCode(code: String?): String? {
        if (code.isNullOrBlank()) return false.let { null }
        val normalized = normalizeCode(code)
        val token = tokensByCode[normalized] ?: return null
        val session = sessionsByToken[token] ?: return null

        if (session.isExpired) {
            revokeSession(token)
            return null
        }
        return token
    }

    /**
     * Revokes an existing session token.
     */
    fun revokeSession(sessionToken: String) {
        val session = sessionsByToken.remove(sessionToken)
        if (session != null) {
            tokensByCode.remove(normalizeCode(session.pairingCode))
        }
    }

    /**
     * Revokes all active sessions.
     */
    fun revokeAll() {
        sessionsByToken.clear()
        tokensByCode.clear()
    }

    /**
     * Returns the active session if present and valid.
     */
    fun getSession(sessionToken: String): PairingSession? {
        val session = sessionsByToken[sessionToken] ?: return null
        if (session.isExpired) {
            revokeSession(sessionToken)
            return null
        }
        return session
    }

    private fun cleanExpired() {
        val now = System.currentTimeMillis()
        val expiredTokens = sessionsByToken.filterValues { it.expiresAt <= now }.keys
        for (token in expiredTokens) {
            revokeSession(token)
        }
    }

    private fun normalizeCode(code: String): String {
        return code.replace("-", "").trim().uppercase()
    }
}
